name: My first github action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2 #we are USEing this action provided by github which clones the repo
      - uses: actions/setup-node@v2
        with:
          node-version: "18.8.0"
      - run: tree #this is bash command
      - run: node -v
      - name: Build the project in the cloud mostly azure
        run: yarn build
      - name: setup finish #name is used to name the run cmd
        run: echo "aythu macha"
