name: My first github action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2 #we are USEing this action provided by github which clones the repo
      - run: tree #this is bash command
